import 'package:topo_app/models/vector.dart';

final carpetas = [
  {
    "displayName": "Todos",
    "type": "Todos",
    "route": "",
    "data": <Vector>[
      Vector(3, "brujula", "VARIOS/BRUJULA.png", 100, 100),
      Vector(4, "linea punteada", "VARIOS/LINEA_PUNTEADA.png", 100, 91),
    ],
  },
  {
    "displayName": "Baño",
    "type": "Baño",
    "route": "BANIO/",
    "data": <Vector>[
      Vector(0, "Bañera", "BAÑERA.png", 100, 119),
      Vector(1, "Lavamanos 1", "LAVAMANOS.jpg", 100, 100),
      Vector(2, "Lavamanos 2", "LAVAMANOS2.jpg", 100, 55),
      Vector(3, "Mueble baño", "MUEBLE_BAÑO.png", 100, 55),
      Vector(4, "Sanitario", "SANITARIO.png", 100, 182),
      Vector(5, "Tina de baño", "TINA_DE_BAÑO.png", 100, 44),
    ],
  },
  {
    "displayName": "Cocina",
    "type": "Cocina",
    "route": "COCINA/",
    "data": <Vector>[
      Vector(0, "Armario de madera inferior", "ARMARI_DE_MADERA_INFERIOR.png", 100,67),
      Vector(1, "Armario de madera superior", "ARMARIO_DE_MADERA_SUPERIOR.png",100,43),
      Vector(2, "Barra", "BARRA.png",100,35),
      Vector(6, "Despensa", "DESPENSA.png",100,79),
      Vector(7, "Estufa", "ESTUFA.png",100,109),
      Vector(9, "Fogones gas", "FOGONES GAS.jpg",100,86),
      Vector(10, "Fregadero", "FREGADERO.png",100,73),
      Vector(11, "Horno", "HORNO.png",100,92),
      Vector(12, "Lavadora", "LAVADORA.png",100,103),
      Vector(13, "Modulo de cajones", "MODULO_DE_CAJONES.png",100,103),
      Vector(14, "Mueble puertas de cristal", "MUEBLE PUERTAS DE CRISTAL.jpg",100,71),
      Vector(15, "Mueble estufa", "MUEBLE_ESTUFA.png",100,73),
      Vector(17, "Nevera 1", "NEVERA.jpg",100,85),
      Vector(18, "Nevera 2", "NEVERA_2.png",100,100),
      Vector(19, "Nevera 3", "NEVERA3.png",100,85),
      Vector(22, "Secadora", "SECADORA.png",100,105),
      Vector(3, "Butaca", "BUTACA.png",100,100),
      Vector(4, "Camara", "CAMARA.png",100,106),
      Vector(5, "Cuchillo", "CUCHILLO.png",100,100),
      Vector(20, "Plato", "PLATO.png",100,100),
      Vector(21, "Sarten", "SARTEN.png", 100,167),
    ],
  },
  {
    "displayName": "Criminalistica",
    "type": "Criminalistica",
    "route": "CRIMINALISTICA/",
    "data": [],
  },
  {
    "displayName": "Exteriores",
    "type": "Exteriores",
    "route": "EXTERIORES/",
    "data": [],
  },
  {
    "displayName": "Habitacion",
    "type": "Habitacion",
    "route": "HABITACION/",
    "data": [],
  },
  {
    "displayName": "Personas",
    "type": "Personas",
    "route": "PERSONAS/",
    "data": [],
  },
  {
    "displayName": "Puertas y ventanas",
    "type": "Puertas y ventanas",
    "route": "PUERTASVENTANAS/",
    "data": [],
  },
  {
    "displayName": "Sala",
    "type": "Sala",
    "route": "SALA/",
    "data": [],
  },
  {
    "displayName": "Vehiculos",
    "type": "Vehiculos",
    "route": "VEHICULOS/",
    "data": [],
  },
  {
    "displayName": "Varios",
    "type": "Varios",
    "route": "VARIOS/",
    "data": [],
  }
];
